// app/layout.js
import "./globals.css";
// ClerkProvider import ko hata diya gaya hai
import LayoutClient from "./LayoutClient";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    // ClerkProvider tags ko bhi hata diya gaya hai
    <html lang="en">
      <body>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}